services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 5s
      timeout: 5s
      retries: 10

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db
    ports:
      - "5432:5432"

  UserService:
    image: gorkinpot/microservices:userservice
    build:
      context: ./UserService
    depends_on:
      rabbitmq:
        condition: service_healthy
      db:
        condition: service_started
    ports:
      - "8081:8081"

  CartService:
    image: gorkinpot/microservices:cartservice
    build:
      context: ./CartService
    depends_on:
      rabbitmq:
        condition: service_healthy
      db:
        condition: service_started
    ports:
      - "8082:8082"

  BookingService:
    image: gorkinpot/microservices:bookingservice
    build:
      context: ./BookingService
    depends_on:
      rabbitmq:
        condition: service_healthy
      db:
        condition: service_started
    ports:
      - "8083:8083"

  CatalogService:
    image: gorkinpot/microservices:catalogservice
    build:
      context: ./CatalogService
    depends_on:
      rabbitmq:
        condition: service_healthy
      db:
        condition: service_started
    ports:
      - "8084:8084"

  CommentService:
    image: gorkinpot/microservices:commentservice
    build:
      context: ./CommentService
    depends_on:
      rabbitmq:
        condition: service_healthy
      db:
        condition: service_started
    ports:
      - "8085:8085"

  DocumentService:
    image: gorkinpot/microservices:documentservice
    build:
      context: ./DocumentService
    depends_on:
      rabbitmq:
        condition: service_healthy
      db:
        condition: service_started
    ports:
      - "8086:8086"

  NotificationService:
    image: gorkinpot/microservices:notificationservice
    build:
      context: ./NotificationService
    depends_on:
      rabbitmq:
        condition: service_healthy
      db:
        condition: service_started
    ports:
      - "8087:8087"

  PaymentService:
    image: gorkinpot/microservices:paymentservice
    build:
      context: ./PaymentService
    depends_on:
      rabbitmq:
        condition: service_healthy
      db:
        condition: service_started
    ports:
      - "8088:8088"

  RoomService:
    image: gorkinpot/microservices:roomservice
    build:
      context: ./RoomService
    depends_on:
      rabbitmq:
        condition: service_healthy
      db:
        condition: service_started
    ports:
      - "8089:8089"
