global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: UserService
    metrics_path: /metrics
    static_configs:
      - targets: ["UserService:8081"]

  - job_name: CartService
    metrics_path: /metrics
    static_configs:
      - targets: ["CartService:8082"]

  - job_name: BookingService
    metrics_path: /metrics
    static_configs:
      - targets: ["BookingService:8083"]

  - job_name: CatalogService
    metrics_path: /metrics
    static_configs:
      - targets: ["CatalogService:8084"]

  - job_name: CommentService
    metrics_path: /metrics
    static_configs:
      - targets: ["CommentService:8085"]

  - job_name: DocumentService
    metrics_path: /metrics
    static_configs:
      - targets: ["DocumentService:8086"]

  - job_name: NotificationService
    metrics_path: /metrics
    static_configs:
      - targets: ["NotificationService:8087"]

  - job_name: PaymentService
    metrics_path: /metrics
    static_configs:
      - targets: ["PaymentService:8088"]

  - job_name: RoomService
    metrics_path: /metrics
    static_configs:
      - targets: ["RoomService:8089"]
